version: '3'
services:
  delugue:
    image: "linuxserver/delugue"
    container_name: delugue
    hostname: delugue
    volumes:
      - "~/docker/delugue/config:/config"
      - "~/docker/delugue/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    ports:
      - "80:80"
      - "6881:6881/udp"
      - "5000:5000"
      - "51413:51413"
    network_mode: "host"
  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    volumes:
      - "~/docker/jackett/config:/config"
      - "~/docker/delugue/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "9117:9117"
  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ="America/Argentina/Buenos_Aires"
      - PLEX_CLAIM="claim-hqSS1q3ss7yH4z1xnSaQ"
      - PUID=1000
      - PGID=1000
    hostname: "DantePlexMediaServer"
    network_mode: "host"
    volumes:
      - "~/docker/plex:/config"
      - "~/docker/sonarr/tvseries:/tv"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/plex:/transcode"

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    ports:
     - "8989:8989"
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "~/docker/sonarr/config:/config"
     - "~/docker/sonarr/tvseries:/tv"
     - "~/docker/delugue/downloads:/downloads"
    environment:
     - PUID=1000
     - PGID=1000
    depends_on:
      - delugue
      - jackett
      - plex

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/docker/radarr/config:/config"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/delugue/downloads:/downloads"
    environment:
     - PUID=1000
     - PGID=1000
    depends_on:
      - delugue
      - jackett
      - plex
