version: '3.8'

services:
  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/jackett/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - main
    ports:
      - "9117:9117"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.jackett.rule=Host(`jackett.${DOMAIN_URL}`)"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.entrypoints=websecure,web"
      - "traefik.http.routers.jackett.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "group=mediaserver"

  plex:
    image: "plexinc/pms-docker:latest"
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
    environment:
      - TZ=${DOCKER_TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - ${MEDIA_LOCATION}:/media
      - /tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_URL}`)"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.entrypoints=websecure,web"
      - "traefik.http.routers.plex.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=32400"
      - "traefik.backend=plex"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:plex.${DOMAIN_URL}"
      - "group=mediaserver"
    networks:
      - main

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/sonarr/config:/config"
      - "${STORAGE_LOCATION}:/docker"
      - ${MEDIA_LOCATION}:/media
      - /mnt/watch:/watch
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_URL}`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure,web"
      - "traefik.http.routers.sonarr.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=8989"
      - "traefik.backend=sonarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
      - "group=mediaserver"
    networks:
      - main

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/radarr/config:/config"
      - "${STORAGE_LOCATION}:/docker"
      - ${MEDIA_LOCATION}:/media
      - /mnt/watch:/watch
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=radarr.${DOMAIN_URL}
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_URL}`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.entrypoints=websecure,web"
      - "traefik.http.routers.radarr.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=7878"
      - "traefik.backend=radarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:radarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
      - "group=mediaserver"

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${DOCKER_TZ}
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/bazarr/config:/config
      - ${MEDIA_LOCATION}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_URL}`)"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.entrypoints=websecure,web"
      - "traefik.http.routers.bazarr.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
      - "traefik.enable=true"
      - "traefik.port=6767"
      - "traefik.backend=bazarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:bazarr.${DOMAIN_URL}"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "group=mediaserver"
    networks:
      - main

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
    volumes:
      - ${STORAGE_LOCATION}/nzbhydra:/config
      - /mnt/watch:/watch
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.nzbhydra.rule=Host(`nzbhydra.${DOMAIN_URL}`)"
      - "traefik.http.routers.nzbhydra.tls=true"
      - "traefik.http.routers.nzbhydra.entrypoints=websecure,web"
      - "traefik.http.routers.nzbhydra.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.nzbhydra.loadbalancer.server.port=5076"
      - "traefik.enable=true"
      - "traefik.port=5076"
      - "traefik.backend=nzbhydra"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:nzbhydra.${DOMAIN_URL}"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "group=mediaserver"
    networks:
      - main
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${STORAGE_LOCATION}/qbittorrent:/config
      - ${STORAGE_LOCATION}/qbittorrent/downloads:/downloads
      - /mnt/watch:/watch
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.qbt.rule=Host(`qbt.${DOMAIN_URL}`)"
      - "traefik.http.routers.qbt.tls=true"
      - "traefik.http.routers.qbt.entrypoints=websecure,web"
      - "traefik.http.routers.qbt.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.qbt.loadbalancer.server.port=8080"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=qbt"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:qbt.${DOMAIN_URL}"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "group=mediaserver"
    networks:
      - main
    ports:
      - 49122:49122
      - 49122:49122/udp
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
    volumes:
      - ${STORAGE_LOCATION}/nzbget/config:/config
      - ${STORAGE_LOCATION}/nzbget/downloads:/downloads
      - /mnt/watch:/watch
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.${DOMAIN_URL}`)"
      - "traefik.http.routers.nzbget.tls=true"
      - "traefik.http.routers.nzbget.entrypoints=websecure,web"
      - "traefik.http.routers.nzbget.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.enable=true"
      - "traefik.port=6789"
      - "traefik.backend=nzbget"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:nzbget.${DOMAIN_URL}"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
      - "group=mediaserver"
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    external: true