version: '3.3'
services:
  # epg:
  #   image: janwer/webgrab
  #   container_name: webgrab
  #   volumes:
  #     - ~/docker/epg/config:/config
  #     - ~/docker/epg/data:/data


  # subtitles-daemon:
  #   image: dantebarba/subliminal-daemon
  #   container_name: subtitles-daemon
  #   volumes:
  #     - ~/docker/radarr/movies:/movies
  #     - ~/docker/sonarr/tvseries:/tv
  #   depends_on:
  #     - sonarr
  #     - radarr
  #     - plex

  # netdata:
  #   image: titpetric/netdata
  #   container_name: netdata
  #   ports:
  #     - "19999:19999"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #   cap_add:
  #     - SYS_PTRACE
  #   environment:
  #     - VIRTUAL_HOST=stats.${DOMAIN_URL}

  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=${DOMAIN_URL}
    depends_on:
      - transmission
      - sonarr
      - jackett
      - radarr
      - plex

  transmission:
    image: "linuxserver/transmission"
    container_name: transmission
    hostname: transmission
    volumes:
      - "~/docker/transmission/config:/config"
      - "~/docker/transmission/downloads:/downloads"
      - "~/docker/transmission/watch:/watch"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=transmission.${DOMAIN_URL}
      - VIRTUAL_PORT=9091
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    volumes:
      - "~/docker/jackett/config:/config"
      - "~/docker/transmission/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=jackett.${DOMAIN_URL}
    ports:
      - "9117:9117"
  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ="America/Argentina/Buenos_Aires"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
      - VIRTUAL_HOST=plex.${DOMAIN_URL}
      - VIRTUAL_PORT=32400
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - "~/docker/plex:/config"
      - "~/docker/sonarr/tvseries:/tv"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/plex:/transcode"

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    ports:
     - "8989:8989"
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "~/docker/sonarr/config:/config"
     - "~/docker/sonarr/tvseries:/tv"
     - "~/docker/transmission/downloads:/downloads"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
    depends_on:
      - transmission
      - jackett
      - plex

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/docker/radarr/config:/config"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/transmission/downloads:/downloads"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=radarr.${DOMAIN_URL}

    depends_on:
      - transmission
      - jackett
      - plex
