version: '2'

services:
  transmission:
    image: "linuxserver/transmission"
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/transmission/config:/config"
      - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
      - "${STORAGE_LOCATION}/transmission/watch:/watch"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=9091"
      - "traefik.backend=transmission"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:transmission.${DOMAIN_URL}"
    networks:
      - main

  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/jackett/config:/config"
      - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - "9117:9117"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=9117"
      - "traefik.backend=jackett"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:jackett.${DOMAIN_URL}"
      - "traefik.basic.protocol=https"
    networks:
      - main

  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ="America/Argentina/Buenos_Aires"
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
      - "${STORAGE_LOCATION}/deezldr/music"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - "${STORAGE_LOCATION}/library:/library"
      - /tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=32400"
      - "traefik.backend=plex"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:plex.${DOMAIN_URL}"
    networks:
      - main


  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    ports:
     - "8989:8989"
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "${STORAGE_LOCATION}/sonarr/config:/config"
     - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
     - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=8989"
      - "traefik.backend=sonarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_URL}"
    networks:
      - main

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/radarr/config:/config"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=radarr.${DOMAIN_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=7878"
      - "traefik.backend=radarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:radarr.${DOMAIN_URL}"
    networks:
      - main

  deezldr:
    image: bocki/deezloaderrmx
    container_name: deezldr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/deezldr/config:/config"
      - "${STORAGE_LOCATION}/deezldr/music:/downloads"
    labels:
      - "traefik.enable=true"
      - "traefik.port=1730"
      - "traefik.backend=deezeldr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:music.${DOMAIN_URL}"
    networks:
      - main

networks:
  main:
    external: true
