version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=danteplexmediaserver.tk
    depends_on:
      - transmission
      - sonarr
      - jackett
      - radarr
      - plex

  transmission:
    image: "linuxserver/transmission"
    container_name: transmission
    hostname: transmission
    volumes:
      - "~/docker/transmission/config:/config"
      - "~/docker/transmission/downloads:/downloads"
      - "~/docker/transmission/watch:/watch"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=transmission.danteplexmediaserver.tk
      - VIRTUAL_PORT=9091
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"

  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    volumes:
      - "~/docker/jackett/config:/config"
      - "~/docker/transmission/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=jackett.danteplexmediaserver.tk
    ports:
      - "9117:9117"
  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ="America/Argentina/Buenos_Aires"
      - PLEX_CLAIM="claim-hqSS1q3ss7yH4z1xnSaQ"
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=plex.danteplexmediaserver.tk
      - VIRTUAL_PORT=32400
    hostname: "DantePlexMediaServer"
    volumes:
      - "~/docker/plex:/config"
      - "~/docker/sonarr/tvseries:/tv"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/plex:/transcode"

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    ports:
     - "8989:8989"
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "~/docker/sonarr/config:/config"
     - "~/docker/sonarr/tvseries:/tv"
     - "~/docker/transmission/downloads:/downloads"
    environment:
     - PUID=1000
     - PGID=1000
     - VIRTUAL_HOST=sonarr.danteplexmediaserver.tk
    depends_on:
      - transmission
      - jackett
      - plex

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    ports:
      - "7878:7878"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "~/docker/radarr/config:/config"
      - "~/docker/radarr/movies:/movies"
      - "~/docker/transmission/downloads:/downloads"
    environment:
     - PUID=1000
     - PGID=1000
    depends_on:
      - transmission
      - jackett
      - plex
