version: '2'

services:
  transmission:
    image: "linuxserver/transmission"
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/transmission/config:/config"
      - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
      - "${STORAGE_LOCATION}/transmission/watch:/watch"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEB_HOME=/combustion-release/
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=9091"
      - "traefik.backend=transmission"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:transmission.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/jackett/config:/config"
      - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - main
    ports:
      - "9117:9117"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=9117"
      - "traefik.backend=jackett"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:jackett.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

  plex:
    image: "plexinc/pms-docker"
    container_name: plex
    restart: unless-stopped
    ports:
      - "3240:32400/tcp"
      - "3005:3005/tcp"
    environment:
      - TZ=${DOCKER_TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
    hostname: ${PLEX_HOSTNAME}
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - ${MEDIA_LOCATION}:/media
      - /tmp:/tmp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=32400"
      - "traefik.backend=plex"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:plex.${DOMAIN_URL}"
    networks:
      - main


  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "${STORAGE_LOCATION}/sonarr/config:/config"
     - "${STORAGE_LOCATION}:/docker"
     - ${MEDIA_LOCATION}:/media
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=8989"
      - "traefik.backend=sonarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main
      
  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/radarr/config:/config"
      - "${STORAGE_LOCATION}:/docker"
      - ${MEDIA_LOCATION}:/media
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=radarr.${DOMAIN_URL}
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=7878"
      - "traefik.backend=radarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:radarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${DOCKER_TZ}
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/bazarr/config:/config
      - ${MEDIA_LOCATION}:/media
    labels:
      - "traefik.enable=true"
      - "traefik.port=6767"
      - "traefik.backend=bazarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:bazarr.${DOMAIN_URL}"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
    networks:
      - main

networks: 
  main:
    external: true



