map "$http_x_plex_product $args" $plex_force_transcode {
    default 0;
    "~Plex for Android \(TV\)" 1;
    "~X-Plex-Product=Plex(%20|\+)for(%20|\+)Android(%20|\+)(\(|%28)TV(\)|%29)" 1;
}

map "$plex_force_transcode $request_uri" $plex_uri {
    default $request_uri;
    "~^1 (?<pre>.*)directPlay=1(?<post>.*)$" "${pre}directPlay=0${post}";
}

server {
    listen 8080;
    resolver 127.0.0.11 valid=30s;

    location / {
        set $plex_upstream http://plex:32400;
        proxy_pass $plex_upstream$plex_uri;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }
}
